import { Router } from "express";
import upload from "../middlewares/upload.js";
import { createContactResume, getContactResume, updateResume, getAllContactResume, allContactResume, deleteResume } from "../Controller/contactResume";
const contactResumeRouter = Router();
contactResumeRouter.post("/create",upload.single("photo"), createContactResume);
contactResumeRouter.post("/update",upload.single("photo"), updateResume);
contactResumeRouter.get("/get-contact/:id", getContactResume);
contactResumeRouter.get("/all-contact/:id", allContactResume);
contactResumeRouter.get("/get-all-contact", getAllContactResume);
contactResumeRouter.delete("/delete-resume/:id", deleteResume);
export default contactResumeRouter;
